[project]
name = "osparc_filecomms"
description = "oSparc file communications"
version = "0.0.1"
authors = [
    {name="Werner Van Geit @ IT'IS Zurich"}
]
license={file="LICENSE.txt"}
readme="README.md"


[project.optional-dependencies]
test = ["pytest", "pytest-mock"]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli = true
log_cli_level = "DEBUG"

[tool.distutils.bdist_wheel]
universal = true
