on:
    push:


jobs:
    wheels:
        name: building wheel
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11
            - name: Build wheel
              run: python -m build
            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                  name: wheels-ubuntu-latest-py3.11
                  path: ./dist/*.whl

    test-pypi:
        name: Publish wheels on Test PyPI
        runs-on: ubuntu-latest 
        needs:
            - wheels
        environment:
            name: osparc-filecomms
            url: https://test.pypi.org/p/osparc-filecomms
        permissions:
            id-token: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: wheels-*
                  path: dist
                  merge-multiple: true
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/


