on:
    push:


jobs:
    call-test-workflow:
        uses: wvangeit/osparc-filecomms/.github/workflows/test.yml@master

    wheels:
        name: building wheel
        runs-on: ubuntu-latest
        needs:
            call-test-workflow
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: python -m pip install --upgrade pip setuptools build
            - name: Build wheel
              run: python -m build
            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                  name: wheels-ubuntu-latest-py3.11
                  path: ./dist/*.whl

    test-pypi:
        name: Publish wheels on PyPI
        runs-on: ubuntu-latest 
        needs:
            - wheels
        environment:
            name: osparc-filecomms
            url: https://test.pypi.org/p/osparc-filecomms
        permissions:
            id-token: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: wheels-*
                  path: dist
                  merge-multiple: true
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/

    pypi:
        name: Publish wheels on Test PyPI
        runs-on: ubuntu-latest 
        needs:
            - test-pypi
        environment:
            name: osparc-filecomms
            url: https://pypi.org/p/osparc-filecomms
        if: github.ref == 'refs/heads/master'
        permissions:
            id-token: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: wheels-*
                  path: dist
                  merge-multiple: true
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
