on:
    push:
        branches:
                - master


jobs:
    call-test-workflow:
        uses: wvangeit/osparc-filecomms/.github/workflows/test.yml@master

    
    wheels:
        name: building wheel
        runs-on: ubuntu-latest
        needs:
            call-test-workflow
        permissions:
            id-token: write
            contents: write    
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: python -m pip install --upgrade pip setuptools build      
            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build wheel
              run: python -m build
            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                  name: wheels-ubuntu-latest-py3.11
                  path: ./dist/*.whl
            - name: Create a GitHub release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ steps.tag_version.outputs.new_tag }}
                  name: Release ${{ steps.tag_version.outputs.new_tag }}
                  body: ${{ steps.tag_version.outputs.changelog }}

    test-pypi:
        name: Publish wheels on Test PyPI
        runs-on: ubuntu-latest 
        needs:
            - wheels
        environment:
            name: osparc-filecomms
            url: https://test.pypi.org/p/osparc-filecomms
        permissions:
            id-token: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: wheels-*
                  path: dist
                  merge-multiple: true
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/

    pypi:
        name: Publish wheels on PyPI
        runs-on: ubuntu-latest 
        needs:
            - test-pypi
        environment:
            name: osparc-filecomms
            url: https://pypi.org/p/osparc-filecomms
        permissions:
            id-token: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: wheels-*
                  path: dist
                  merge-multiple: true
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
